spring:
  application:
    name: temperatura-converter-service
server:
  port: 9001
  servlet:
    context-path: /temperatura
eureka:
  client:
    serviceUrl:
      defaultZone: '${EUREKA_URI:http://desenv:desenv@localhost:8761/eureka}'
  instance:
    preferIpAddress: true
